package cn.chen.assimp.render
import com.mojang.blaze3d.GpuFormat
import com.mojang.blaze3d.PrimitiveTopology
import com.mojang.blaze3d.pipeline.BindGroupLayout
import com.mojang.blaze3d.pipeline.BlendFunction
import com.mojang.blaze3d.pipeline.ColorTargetState
import com.mojang.blaze3d.pipeline.DepthStencilState
import com.mojang.blaze3d.pipeline.RenderPipeline
import com.mojang.blaze3d.platform.CompareOp
import com.mojang.blaze3d.shaders.UniformType
import com.mojang.blaze3d.vertex.VertexFormat
import net.minecraft.client.renderer.BindGroupLayouts
object AIPipelines {
    const val MAX_BONES = 128
    val BONE_MATRICES_LAYOUT: BindGroupLayout = BindGroupLayout.builder()
        .withUniform("BoneMatrices", UniformType.UNIFORM_BUFFER)
        .build()
    val MATERIAL_FACTORS_LAYOUT: BindGroupLayout = BindGroupLayout.builder()
        .withUniform("MaterialFactors", UniformType.UNIFORM_BUFFER)
        .build()
    val OBJECT_MATRICES_LAYOUT: BindGroupLayout = BindGroupLayout.builder()
        .withUniform("ObjectMatrices", UniformType.UNIFORM_BUFFER)
        .build()
    val SHADOW_LAYOUT: BindGroupLayout = BindGroupLayout.builder()
        .withUniform("ShadowData", UniformType.UNIFORM_BUFFER)
        .withSampler("ShadowMap")
        .build()
    val SHADOW_DATA_LAYOUT: BindGroupLayout = BindGroupLayout.builder()
        .withUniform("ShadowData", UniformType.UNIFORM_BUFFER)
        .build()
    val NORMAL_MAP_LAYOUT: BindGroupLayout = BindGroupLayout.builder()
        .withSampler("NormalMap")
        .build()
    val MR_MAP_LAYOUT: BindGroupLayout = BindGroupLayout.builder()
        .withSampler("MetallicRoughnessMap")
        .build()
    val EMISSIVE_MAP_LAYOUT: BindGroupLayout = BindGroupLayout.builder()
        .withSampler("EmissiveMap")
        .build()
    val IBL_LAYOUT: BindGroupLayout = BindGroupLayout.builder()
        .withSampler("IrradianceMap")
        .withSampler("PrefilterMap")
        .withSampler("BrdfLut")
        .build()
    val DYNAMIC_LIGHTS_LAYOUT: BindGroupLayout = BindGroupLayout.builder()
        .withUniform("DynamicLights", UniformType.UNIFORM_BUFFER)
        .build()
    val WORLD_PROBE_LAYOUT: BindGroupLayout = BindGroupLayout.builder()
        .withSampler("ProbeMap")
        .withUniform("WorldProbe", UniformType.UNIFORM_BUFFER)
        .build()
    val PBR_VERTEX_FORMAT: VertexFormat = VertexFormat.builder(0)
        .addAttribute("Position", GpuFormat.RGB32_FLOAT)
        .addAttribute("Color", GpuFormat.RGBA8_UNORM)
        .addAttribute("UV0", GpuFormat.RG32_FLOAT)
        .addAttribute("UV1", GpuFormat.RG16_SINT)
        .addAttribute("UV2", GpuFormat.RG16_SINT)
        .addAttribute("Normal", GpuFormat.RGBA8_SNORM)
        .addAttribute("Tangent", GpuFormat.RGBA8_SNORM)
        .addAttribute("BoneIds", GpuFormat.RGBA8_UINT)
        .addAttribute("BoneWeights", GpuFormat.RGBA8_UNORM)
        .build()
    val PBR_SNIPPET: RenderPipeline.Snippet = run {
        val matsSnippet = RenderPipeline.builder()
            .withBindGroupLayout(BindGroupLayouts.MATRICES_PROJECTION)
            .withBindGroupLayout(BindGroupLayouts.FOG)
            .withBindGroupLayout(BindGroupLayouts.LIGHTING)
            .buildSnippet()
        RenderPipeline.builder(matsSnippet)
            .withVertexShader("core/ai_pbr")
            .withFragmentShader("core/ai_pbr")
            .withBindGroupLayout(BindGroupLayouts.SAMPLER0)
            .withBindGroupLayout(BindGroupLayouts.SAMPLER1)
            .withBindGroupLayout(BindGroupLayouts.SAMPLER2)
            .withBindGroupLayout(BONE_MATRICES_LAYOUT)
            .withBindGroupLayout(OBJECT_MATRICES_LAYOUT)
            .withBindGroupLayout(MATERIAL_FACTORS_LAYOUT)
            .withBindGroupLayout(SHADOW_LAYOUT)
            .withBindGroupLayout(NORMAL_MAP_LAYOUT)
            .withBindGroupLayout(MR_MAP_LAYOUT)
            .withBindGroupLayout(EMISSIVE_MAP_LAYOUT)
            .withBindGroupLayout(IBL_LAYOUT)
            .withBindGroupLayout(DYNAMIC_LIGHTS_LAYOUT)
            .withBindGroupLayout(WORLD_PROBE_LAYOUT)
            .withVertexBinding(0, PBR_VERTEX_FORMAT)
            .withPrimitiveTopology(PrimitiveTopology.QUADS)
            .withDepthStencilState(DepthStencilState.DEFAULT)
            .buildSnippet()
    }
    val PBR_OPAQUE: RenderPipeline = RenderPipeline.builder(PBR_SNIPPET)
        .withLocation("pipeline/ai_pbr_opaque")
        .withShaderDefine("ALPHA_CUTOUT", 0.01f)
        .withCull(false)
        .build()
    val PBR_OPAQUE_CULL: RenderPipeline = RenderPipeline.builder(PBR_SNIPPET)
        .withLocation("pipeline/ai_pbr_opaque_cull")
        .withShaderDefine("ALPHA_CUTOUT", 0.01f)
        .withCull(true)
        .build()
    val PBR_TRANSLUCENT: RenderPipeline = RenderPipeline.builder(PBR_SNIPPET)
        .withLocation("pipeline/ai_pbr_translucent")
        .withColorTargetState(ColorTargetState(BlendFunction.TRANSLUCENT))
        .withCull(false)
        .withDepthStencilState(DepthStencilState(CompareOp.GREATER_THAN_OR_EQUAL, true))
        .build()
    private val SHADOW_SNIPPET: RenderPipeline.Snippet = RenderPipeline.builder()
        .withVertexShader("core/ai_shadow")
        .withFragmentShader("core/ai_shadow")
        .withBindGroupLayout(BindGroupLayouts.SAMPLER0)
        .withBindGroupLayout(BONE_MATRICES_LAYOUT)
        .withBindGroupLayout(OBJECT_MATRICES_LAYOUT)
        .withBindGroupLayout(MATERIAL_FACTORS_LAYOUT)
        .withBindGroupLayout(SHADOW_DATA_LAYOUT)
        .withVertexBinding(0, PBR_VERTEX_FORMAT)
        .withPrimitiveTopology(PrimitiveTopology.QUADS)
        .withDepthStencilState(DepthStencilState(CompareOp.LESS_THAN_OR_EQUAL, true, 1.5f, 2.0f))
        .withUnusedColorTargetState(0)
        .withCull(false)
        .buildSnippet()
    val SHADOW_CASCADE: Array<RenderPipeline> = Array(AIShadowBuffer.CASCADES) { i ->
        RenderPipeline.builder(SHADOW_SNIPPET)
            .withLocation("pipeline/ai_shadow_$i")
            .withShaderDefine("SHADOW_CASCADE", i)
            .build()
    }
    const val PBR_VERT_STRIDE = 48
}
