name: blaze3d-assimp build
on:
  push:
    branches: [26.2-vulkan]
  pull_request:
    branches: [26.2-vulkan]
jobs:
  build:
    runs-on: ubuntu-24.04
    name: bazel fabric mod
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup java 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: setup bazelisk
        run: |
          curl -L -o bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
          chmod +x bazel
      - name: build fabric mod
        run: ./bazel --output_user_root="$RUNNER_TEMP/bazel-root" --noworkspace_rc build --java_runtime_version=local_jdk --tool_java_runtime_version=local_jdk --java_language_version=25 --tool_java_language_version=25 //:fabric_mod
      - name: upload fabric mod
        uses: actions/upload-artifact@v7
        with:
          name: blaze3d-assimp-1.0.0
          path: bazel-bin/blaze3d-assimp-1.0.0.jar
