name: build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: setup bazelisk
        run: |
          curl -L -o bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
          chmod +x bazel
      - name: build
        run: ./bazel --output_user_root="$RUNNER_TEMP/bazel-root" --noworkspace_rc build --java_runtime_version=local_jdk --tool_java_runtime_version=local_jdk --java_language_version=25 --tool_java_language_version=25 //:fabric_mod
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: bazel-bin/lwjgl-assimp-1.0.0.jar
